---
title: "Location Of Coffee Project"
author: "Elvis Dang"
date: "October 28, 2019"
output: html_document
---

```{r setup, include=FALSE}
##install.packages("tidyverse")
##install.packages("janitor")
##install.packages("ggmap")
##install.packages("maps")
##install.packages("tmap")
##install.packages("spData")
##install.packages("sf")
##install.packages("devtools")
##install.packages("ggrepel")
library(ggrepel)
library(tidyverse)
library(readxl)
library(janitor)
library(ggmap)
library(plyr)
library(viridis)
library(ggplot2)

register_google(key = "AIzaSyCtcLhancA0HzAk9pDdKV1H9vMIeliHipo")
```

```{r, eval = FALSE}
## Cleanning and combining starbucks and dunkin donut data sets

coffee_Starbucks <- read_xlsx("week6_coffee_chains.xlsx", sheet = 1) %>%
  clean_names() 
coffee_Dunkin <- read_xlsx("week6_coffee_chains.xlsx", sheet = 3) %>%
  clean_names() 
coffee_Starbucks <- rename(coffee_Starbucks, replace = c("state_province" = "state"))
coffee_Dunkin <- rename(coffee_Dunkin, replace = c("biz_name" = "brand", "e_address" = "street_address", "e_city" = "city", "e_state" = "state", "loc_lat_centroid" = "latitude", "loc_long_centroid" = "longitude", "e_country" = "country"))
coffee_Starbucks <- coffee_Starbucks %>% filter(country == "US", brand == "Starbucks")
coffee_Dunkin <- coffee_Dunkin %>% mutate(brand = recode(brand, "Donuts Dunkin" = "Dunkin' Donuts", "Dunkin' Donuts/Baskin Robbins" = "Dunkin' Donuts", "Dunkin' Donuts-baskln Robbins" = "Dunkin' Donuts", "Dunkin' Donuts Center" = "Dunkin' Donuts", "Dunkin Donuts-baskin Robbin" = "Dunkin' Donuts", "Dunkin Donuts-baskln Robbins" = "Dunkin' Donuts", "Dunkin Donuts-baskin Robbins" = "Dunkin' Donuts", "Dunkin Donuts/Baskin Robbins" = "Dunkin' Donuts", "Dunkin Donuts/Togo's" = "Dunkin' Donuts", "Dunkin Donuts Distribution Center" = "Dunkin' Donuts", "Dunkin Donuts-wilmington" = "Dunkin' Donuts", "Dunkin Donuts-baskin Robblns" = "Dunkin' Donuts"))
coffee_Dunkin <- coffee_Dunkin %>% filter(brand == "Dunkin' Donuts")
coffee_Starbucks <- coffee_Starbucks %>% select(coffee_Starbucks = -c(store_number , store_name, ownership_type, postcode, phone_number, timezone))
coffee_Dunkin <- coffee_Dunkin %>% select(coffee_Dunkin = -c(e_postal, e_zip_full, loc_county, loc_area_code, loc_fips, loc_msa, loc_pmsa, loc_tz, loc_dst, loc_lat_poly, loc_long_poly, biz_info, biz_phone, web_url, id))
coffee_Dunkin_Starbucks <- rbind(coffee_Dunkin, coffee_Starbucks)
```

```{r, eval = FALSE}
## View combine data set
glimpse(coffee_Dunkin_Starbucks)
count(coffee_Dunkin_Starbucks, vars = "brand")
## Count top states with coffee locations
count_state_Dunkin <- coffee_Dunkin_Starbucks %>% filter(brand == "Dunkin' Donuts") %>% count(vars = ("state"))  %>% mutate(brand = "Dunkin' Donuts")

```

```{r, eval = FALSE}
coors_state <- coffee_Dunkin_Starbucks %>% group_by(state) %>%
  summarise(longitude = mean(longitude), latitude = mean(latitude))
coors_state
count_state_Dunkin <- count_state_Dunkin %>% arrange(desc(freq))
Top8_Dunkin <- count_state_Dunkin %>% filter(freq > 200)
count_state_Starbucks <- coffee_Dunkin_Starbucks %>% filter(brand == "Starbucks") %>% count(vars = ("state"))  %>% mutate(brand = "Starbucks")
count_state_Starbucks <- count_state_Starbucks %>% arrange(desc(freq))
Top8_Starbucks <- count_state_Starbucks %>% filter(freq > 450)
Top8_Dunkin
Top8_Starbucks
Top8 <- rbind(Top8_Dunkin, Top8_Starbucks)
```
```{r Coffee Map, eval = T}
## Plot graph

##Deepal Silva's Coffee Map
##ggplot(data=coffee_Dunkin_Starbucks, aes(longitude, latitude)) +
##  borders("usa") +
##  geom_point(color = "#007706", alpha = 0.3)+
##  coord_equal() +
##  facet_wrap(~ brand)


US_map<-get_map(location='united states', source = "google", zoom=2, maptype = "roadmap",na.rm = T, color = "bw", ) 

coffeeMap <- ggmap(US_map, extent = "device", maprange = TRUE, show.legend = FALSE) 


coffeeMap <- coffeeMap + geom_point(aes(x = longitude, y = latitude, color = brand), data = coffee_Dunkin_Starbucks, alpha = .5, size = 1, show.legend = FALSE) +
  facet_wrap(~ brand)

coffeeMap <- coffeeMap + scale_colour_manual(values = c("Starbucks" = "green4", "Dunkin' Donuts" = "violetred2"))

coffeeMap <- coffeeMap + scale_y_continuous(limits=c(15, 70)) + scale_x_continuous(limits=c(-160, -60))

coffeeMap2 <- coffeeMap + stat_density2d(aes(x=longitude, y = latitude, fill =..level.., alpha = ..level..), data = coffee_Dunkin_Starbucks, geom="polygon", bins = 20) + scale_fill_gradient(low = "black", high = "yellow") + theme(legend.position = "None") + ggtitle("Location of Coffee Shops") + theme(plot.title = element_text(lineheight = 3.5, face = "bold")) +
theme(plot.title = element_text(hjust = 0.5)) +
theme(axis.line=element_blank())+                     theme(axis.text.x=element_blank())+                   theme(axis.text.y=element_blank())+                   theme(axis.ticks=element_blank())

coffeeMap
coffeeMap2
```